feat: add header menu component AB#18868
global-121/121-platform pull request #3818
Opened 2023-04-18 15:28 UTC by agnesesaulite

2023-04-19 12:02 UTC, elwinschmitz requested changes

2023-04-19 12:12 UTC, agnesesaulite commented on interfaces/HO-Portal/src/app/components/header/header.component.scss
> +  background: #ffffff;
@elwinschmitz Where are variables defined?

2023-04-20 07:14 UTC, agnesesaulite commented on interfaces/HO-Portal/src/app/components/header/header.component.html
> +                  <ion-label>Home</ion-label>
Thanks! Done!

2023-04-20 07:14 UTC, agnesesaulite commented on interfaces/HO-Portal/src/app/components/header/header.component.html
> +                  <ion-label>Users</ion-label>
As well.

2023-04-20 07:14 UTC, agnesesaulite commented on interfaces/HO-Portal/src/app/components/header/header.component.html
> +                  <ion-label>Help</ion-label>
As well.

2023-04-20 07:14 UTC, agnesesaulite commented on interfaces/HO-Portal/src/app/components/header/header.component.html
> -          {{ title }}
Added back.

2023-04-20 07:15 UTC, agnesesaulite commented on interfaces/HO-Portal/src/app/components/header/header.component.scss
> +  background: #ffffff;
fixed

2023-04-20 09:47 UTC, kaspars-grinbergs-accenture approved these changes

2023-04-20 13:49 UTC, elwinschmitz approved these changes

2023-04-20 13:50 UTC, merged