New feature added for manual testing PBI#18557
global-121/121-platform pull request #3936
Opened 2023-05-25 11:52 UTC by girtsfre

Created a feature file with test scenarios for testing in Swagger

2023-05-25 12:29 UTC, TatevAccenture submitted a review, later dismissed

2023-05-30 07:33 UTC, jannisvisser requested changes
these are just some minor changes. if they're changed, i'll approve it.

2023-05-30 07:33 UTC, jannisvisser commented on features/Other/Edit_Info_Person_Affected_From_EspoCRM.feature
> +    And the user has filled in values for "NewFspAttributes"
I believe the idea here is that there can only 1 'When' statement (and thus that there cannot be 'And's after a 'When'), as the 'When' should really pinpoint 1 specific action that is done by the user in a scenario. So all 'preparation' before this action should be under 'Given'. (Same for the other scenarios below.)

2023-05-30 07:33 UTC, jannisvisser commented on features/Other/Edit_Info_Person_Affected_From_EspoCRM.feature
> +    Given the "refferenceId" is provided
```suggestion
    Given the "referenceId" is provided
```

2023-05-30 07:33 UTC, jannisvisser commented on features/Other/Edit_Info_Person_Affected_From_EspoCRM.feature
> +    Given the "refferenceId" is provided
same change for other scenarios below

2023-05-30 09:50 UTC, jannisvisser approved these changes

2023-05-30 09:51 UTC, merged