Fix.accordion UI alignment AB#23050
global-121/121-platform pull request #4266
Opened 2023-08-29 13:08 UTC by agnesesaulite

Align the payment row layout with rest of activity overview

2023-08-30 14:15 UTC, kaspars-grinbergs-accenture approved these changes

2023-08-31 09:14 UTC, PeterSmallenbroek requested changes

2023-08-31 09:23 UTC, agnesesaulite commented on interfaces/HO-Portal/src/app/components/registration-activity-overview/registration-activity-overview.component.ts
> +          false,
@PeterSmallenbroek  We don't need to show it in activity overview and that was my solution for that. Can you suggest better ones?

2023-09-01 06:44 UTC, agnesesaulite commented on interfaces/HO-Portal/src/app/enums/date-format.enum.ts
> +  dayAndTime = 'dd-MM-yyyy, HH:mm',
@PeterSmallenbroek ok, if I add new enum will it help? At least I tested it and it doesn't brake sorting. Or better to leave date as is?

2023-09-04 08:41 UTC, PeterSmallenbroek commented on interfaces/HO-Portal/src/app/enums/date-format.enum.ts
> +  dayAndTime = 'dd-MM-yyyy, HH:mm',
You can make a new enum and use that. And then revert this above change

2023-09-05 11:12 UTC, PeterSmallenbroek approved these changes

2023-09-05 11:12 UTC, merged