Additional refactorings in Portal on SSO-branch  AB#27415
global-121/121-platform pull request #5125
Opened 2024-04-09 14:47 UTC by elwinschmitz

2024-04-30 12:58 UTC, PeterSmallenbroek requested changes

2024-04-30 12:58 UTC, PeterSmallenbroek commented on interfaces/Portal/src/assets/i18n/en.json
> +        "label": "121 uses Single Sign-On (SSO) to securely authenticate and log you in to the portal."
In review with SPD lets change this to: `121 Portal uses Single Sign-On (SSO) to securely authenticate and log in all (121 & Redline) users.`

2024-04-30 13:24 UTC, elwinschmitz commented on interfaces/Portal/src/app/auth/auth.service.ts
> +      today.getUTCDate() === issuedDate.getUTCDate()
There is indeed the false-positive of "2024-04-13" matching "2024-05-13" indeed...

The main issue was the "local time" vs. "UTC time"; but I apparently 'minified' my solution a bit too much..

2024-05-03 07:05 UTC, PeterSmallenbroek submitted a review, later dismissed

2024-05-03 07:31 UTC, PeterSmallenbroek approved these changes

2024-05-03 07:31 UTC, aberonni approved these changes

2024-05-03 07:32 UTC, merged