fix: registrations not allowed without csv import if program is not published yet AB#27479
global-121/121-platform pull request #5198
Opened 2024-04-25 09:28 UTC by ashishkumarbasak-accenture

fix: registrations not allowed without csv import if program is not published yet [AB#27479](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/27479)

Task: https://dev.azure.com/redcrossnl/121%20Platform/_workitems/edit/27479

2024-04-25 14:14 UTC, Vladimir-Petkov commented
@ashishkumarbasak-accenture I think you don`t have to change seed-data programs.

2024-04-26 08:50 UTC, Vladimir-Petkov submitted a review, later dismissed

2024-04-30 13:43 UTC, RubenGeo requested changes
- Functionally works as expected :)
- I discussed with Tijs that it is no problem if we set all program json files to published = true (than you revert most of the api test changes)
- I think it makes sense to also cover your error in an API test or a unit test:
  - An api test could be added for example to test/registrations/import-registration.test.ts. Where you unpublish a program and that see if you get the 404 error

2024-05-03 07:38 UTC, ashishkumarbasak-accenture commented
> * Functionally works as expected :)
> * I discussed with Tijs that it is no problem if we set all program json files to published = true (than you have to revert most of the api test changes unfortunately)
> * I think it makes sense to also cover your error in an API test or a unit test:
>   
>   * An api test could be added for example to test/registrations/import-registration.test.ts. Where you unpublish a program and that see if you get the 404 error

Updated the MR accordingly, Thanks for your review! 😊

2024-05-03 08:04 UTC, RubenGeo approved these changes
Thanks!

2024-05-03 08:41 UTC, merged