fix: physical card status color AB#28503
global-121/121-platform pull request #5375
Opened 2024-06-04 09:05 UTC by arsforza

AB#28503

## Describe your changes

Brief description of your changes - not in-depth because the bulk of the description should be in the task on DevOps.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added tests wherever relevant
- [ ] I have made sure that all automated checks pass before requesting a review
- [ ] I do not need any deviation from our PR guidelines

2024-06-05 13:13 UTC, aberonni requested changes
Small typo but for the rest looks pretty straightforward ✌️

2024-06-05 13:13 UTC, aberonni commented on interfaces/Portal/src/app/components/registration-physical-card-overview/registration-physical-card-overview.component.scss
> +.pysical-card-number {
```suggestion
.physical-card-number {
```

2024-06-05 13:13 UTC, aberonni commented on interfaces/Portal/src/app/components/registration-physical-card-overview/registration-physical-card-overview.component.html
> +            class="pysical-card-number util--half-margin-end"
```suggestion
            class="physical-card-number util--half-margin-end"
```

2024-06-10 10:27 UTC, elwinschmitz approved these changes
I think it would be even better to have a dedicated component for this (so we only have to do the "status-to-classname"-magic in 1 place;

But for now this is already an improvement. ;)

2024-06-10 10:39 UTC, merged