Refactor Intersolve Visa DTOs
global-121/121-platform pull request #5551
Opened 2024-07-08 14:26 UTC by PeterSmallenbroek

## Describe your changes

Brief description of your changes - not in-depth because the bulk of the description should be in the task on DevOps.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added tests wherever relevant
- [ ] I have made sure that all automated checks pass before requesting a review
- [ ] I do not need any deviation from our PR guidelines

2024-07-11 14:16 UTC, diderikvw requested changes
Great job Peter! With all the work you did, you made reviewing very easy, and I could nitpick a lot :)
I suggest to go through all comments first, including some conversation probably on some of them, update/tune our draft guidelines if needed, before starting to change code.

2024-07-11 14:16 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/intersolve-visa/interfaces/contact-information-params.interface.ts
Looks like this interface is only used as partial, so remove the "Params" suffix and put into interfaces/partials?

2024-07-11 14:16 UTC, diderikvw commented on services/121-service/src/registration/registrations.service.ts
![image](https://github.com/global-121/121-platform/assets/1377493/3ef9018b-eecd-429f-be78-6f77d45a46f6)

There seems to be a problem with fieldNames

2024-07-11 14:16 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/intersolve-visa/enum/intersolve-visa-payment-info.enum.ts
Do we also want to rename folder /enum to /enums? :)

2024-07-11 14:16 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/intersolve-visa/interfaces/intersolve-visa-do-transfer-or-issue-card-return-type.interface.ts
I think we can lose the "IntersolveVisa" prefix, just like we do not have it with ReissueCardParams.

2024-07-11 14:16 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/intersolve-visa/interfaces/intersolve-visa-do-transfer-or-issue-card-params.interface.ts
I think we can lose the "IntersolveVisa" prefix, just like we do not have it with ReissueCardParams.

2024-07-11 14:16 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/intersolve-visa/interfaces/send-updated-contact-information-params.interface.ts
> +export interface sendUpdatedContactInformationParams {
Start with a capital letter, just like the other interfaces.

2024-07-12 07:10 UTC, PeterSmallenbroek commented on services/121-service/src/payments/fsp-integration/intersolve-visa/dtos/intersolve-get-wallet-transactions.dto.ts
> +export interface IntersolveGetTransactionsResponseDataDto {
This will be a partial & should have 'readonly'

2024-07-17 12:40 UTC, merged