Status change popup
global-121/121-platform pull request #6017
Opened 2024-11-04 09:38 UTC by PeterSmallenbroek

AB#30837 

## Describe your changes

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added tests wherever relevant
- [ ] I have made sure that all automated checks pass before requesting a review
- [ ] I do not need any deviation from our PR guidelines

2024-11-08 13:02 UTC, aberonni commented on interfaces/Portalicious/src/locale/messages.xlf
> +        <source>areYouSure</source>
This seems like an error?

2024-11-08 13:02 UTC, aberonni commented on interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.html
> +      i18n-label="@@generic-ok"
```suggestion
      label="Cancel"
      i18n-label="@@generic-cancel"
```

Better IMHO but I don't feel strongly about it

2024-11-12 09:52 UTC, aberonni requested changes
Some more minor things.

2024-11-12 09:52 UTC, aberonni commented on interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
> +    }
```suggestion
    if (messageData && 'customMessage' in messageData) {
      body.message = messageData.customMessage;
    } else if (messageData) {
      body.messageTemplateKey = messageData.messageTemplateKey;
    }
```

Maybe slightly easier to read?

2024-11-12 09:52 UTC, aberonni commented on interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
> +    };
```suggestion
    let body: RegistrationStatusPatchDto = {
      status,
    };
```

Bit of a nitpick but not sure why it needs a separate line.

2024-11-12 09:52 UTC, aberonni commented on interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-custom-message/change-status-contents-with-custom-message.component.html
> +  </div>
@PeterSmallenbroek looks like you forgot to reference the new component here.

2024-11-12 10:59 UTC, PeterSmallenbroek commented on interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-custom-message/change-status-contents-with-custom-message.component.ts
> +    this.previewData.set(undefined);
```suggestion
```

2024-11-12 11:03 UTC, PeterSmallenbroek commented on interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts
> +    }
```suggestion
```

2024-11-12 11:05 UTC, PeterSmallenbroek commented on interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts
> +    this.status.set(status);
See AB#31286

2024-11-12 11:12 UTC, aberonni commented on interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.html
> +  i18n-header
```suggestion
  i18n-header="@@generic-warning"
```

2024-11-12 11:39 UTC, aberonni approved these changes

2024-11-12 12:09 UTC, aberonni approved these changes

2024-11-12 12:09 UTC, merged