Scoped repo refactor
global-121/121-platform pull request #6270
Opened 2024-12-09 14:14 UTC by RubenGeo

[AB#32022](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32022) 

This refactor is needed because we sort of initialized scoped repository twice in the old appoach:

```
 export class RegistrationDataScopedRepository extends ScopedRepository<RegistrationAttributeDataEntity> {
  constructor(
    @Inject(REQUEST) request: ScopedUserRequest,
    @InjectRepository(RegistrationAttributeDataEntity)
    scopedRepository: ScopedRepository<RegistrationAttributeDataEntity>,
  ) {
    super(request, scopedRepository);
  }
```

Here `RegistrationDataScopedRepository` already extents `ScopedRepository` passing it in as argument in the constructor is giving ScopedRepository another ScopedRepository. It's like wrapping it twice.  I think it never gave us issues because the internal defined methods (like 'findOne') are also overwritten twice. 

## Describe your changes

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have added tests wherever relevant
- [x] I have made sure that all automated checks pass before requesting a review
- [x] I do not need any deviation from our PR guidelines

2024-12-10 15:22 UTC, PeterSmallenbroek requested changes

2024-12-10 15:22 UTC, PeterSmallenbroek commented on services/121-service/src/events/event.repository.ts
> +    repository: ScopedRepository<EventEntity>,
```suggestion
    repository: Repository<EventEntity>,
```

2024-12-10 15:44 UTC, RubenGeo commented on services/121-service/src/scoped.repository.ts
> +    if (repository instanceof ScopedRepository) {
@aberonni

2024-12-10 15:53 UTC, aberonni commented on services/121-service/src/scoped.repository.ts
> +    if (repository instanceof ScopedRepository) {
Maybe

```ts

type NotScopedRepository<T extends ObjectLiteral, R = Repository<T>> =
  R extends ScopedRepository<T> ? never : R;

// ... 

private repository: NotScopedRepository<T>,

```

2024-12-11 08:33 UTC, aberonni commented on services/121-service/src/scoped.repository.ts
> +    if (repository instanceof ScopedRepository) {
```ts
type NotScopedRepository<R extends Repository<T>, T extends ObjectLiteral> =
  R extends ScopedRepository<T> ? never : R;
  
  // ...
  
  private repository: NotScopedRepository<Repository<T>, T>,
  ```
  
@RubenGeo I can't tell if this works or not - if not, then I'd say it's fine to leave the runtime error

2024-12-13 14:46 UTC, RubenGeo commented on services/121-service/src/scoped.repository.ts
> +    if (repository instanceof ScopedRepository) {
Unfortunately typescipt is not complaining when I now construct with a ScoperRepository. So merging it now

2024-12-19 15:34 UTC, PeterSmallenbroek approved these changes

2024-12-19 15:56 UTC, merged