Added nedbank to fsp enum to add an initial commit
global-121/121-platform pull request #6293
Opened 2024-12-16 13:22 UTC by RubenGeo

AB#30631 

## Describe your changes

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added tests wherever relevant
- [ ] I have made sure that all automated checks pass before requesting a review
- [ ] I do not need any deviation from our PR guidelines

2025-01-10 16:00 UTC, diderikvw requested changes
Almost mid-way through, already delivering to Ruben for processing.

2025-01-10 16:53 UTC, RubenGeo commented on services/121-service/src/financial-sync/financial-sync-service.ts
> +          await this.nedbankService.retrieveAndUpdateVoucherStatus(
Good point. :) We could do with only orderCreateReference. But than it's probably smart to index orderCreateReference in the database as you would need it for the update statement. Which would be a minor performance degradation on inserting new voucher (it's best to only index columns if it's needed) ... and removing it here as a param would be a minor improvement to the readability of the function. However for a reader it's immediately clear that id is a unique field unlike orderCreateReference. 

So I would be fine leaving it like this, unless you have a strong opinion.

2025-01-10 17:11 UTC, RubenGeo commented on services/121-service/src/financial-sync/financial-sync-service.ts
> +              'Voucher has been refunded by Nedbank. Please contact Nedbank support.', // TODO: is this the correct ux copy?
I updated the UX copy.

We don't have an automated test for that. It's also hard to make since at the moment we cannot send custom content to the GET `v1/orders/references` endpoint. So we cannot tell our mock service to return something else than REDEEMED at this point. You can only manually replace the orderCreateReference in the database to mock. 

I think it would be nice to come up with some way to influence this. The easy way I can think of doing this would be to add:
```
if (process.env.NEBANK_MOCK) {
   orderCreateReference = `${orderCreateReference} - {phoneNumber}`
}
```
somewhere in the code. But this is not ideal as that mocking code than lives in our NedbankService.

2025-01-10 17:23 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
> +import { generateUUIDFromSeed } from '@121-service/src/payments/payments.helpers';
The functions could go to:

shared/utils/uuid.ts
src/shared/services/custom-http.service.ts

2025-01-10 17:24 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/dto/nedbank-create-order-payload.dto.ts
> +        Amount: string;
Nope :(, I added a comment to clarify this.

2025-01-10 17:27 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/dto/nedbank-create-order-payload.dto.ts
> +        SecondaryIdentification: string;
I got an error when not sending that field. I set it to one in the api.service.ts

2025-01-10 17:31 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/dto/nedbank-create-order-response.dto.ts
> +// I prefixed the names with Nedbank to avoid any confusion with other services (this is convienent with auto-import and finding files with cmd+p)
I prefixed all interface names with Nedbank. I left that comment there as clarification for the reviewer but it should be removed later on

2025-01-13 16:21 UTC, diderikvw requested changes
Delivering review of Nedbank Module, except for unit tests. Small refactor stuff I think, except for the idempotency key, which may need a conversation to decide on what is optimal.

2025-01-13 16:21 UTC, diderikvw commented on services/121-service/src/queues-registry/queues-registry.module.ts
> +        max: 5, // Max number of jobs processed
Why 5?

2025-01-13 16:21 UTC, diderikvw commented on services/121-service/src/queues-registry/queues-registry.module.ts
> +        duration: 1000, // per duration in milliseconds
Why 1000?

2025-01-14 14:02 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/interfaces/nedbank-create-order-params.ts
> +export interface NedbankCreateOrderParams {
I changed it to NedbankCreateVoucherParams for now. I think it adds value to have the 'Nedbank' in there because:
- it's easier to find using cmd + p
- If you are in another module and you auto import it it's clear that these params come from out nedbank integration and you are looking at the wrong import.

2025-01-14 14:13 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/interfaces/nedbank-create-order-params.ts
> +  transactionReference: string;
Good point. I am thinking it may be easiest to follow the example of safaricom where it's just named the originatorConversationId which is the same name as what safaricom uses for that parameter.

So for nedbank just name it `orderCreateReference` I think this is the easiest approach if you later on need to fix something related to this.

2025-01-14 14:23 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/interfaces/nedbank-create-order-return.ts
> +export interface NedbankCreateOrderReturn {
I renamed it to `NedbankCreateOrderReturnType` if left nedbank in the because [of](https://github.com/global-121/121-platform/pull/6293#discussion_r1914865813).

Why do we use ReturnType instead of Return?

2025-01-14 14:28 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/interfaces/nedbank-create-order-return.ts
> +  orderCreateReference: string;
I am not sure I follow you here. Do you mean we should use the generateUUIDFromSeed in the processNedbankTransactionJob function and only return the status from the Nedbank.createOrder fuction?

2025-01-14 14:39 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.ts
> +    const cashoutResult = await this.nedbankApiService.createOrder({
Good point. I first started codng and naming everythinh cashout because of Nedbank names it's API the CashOutApi https://apim.nedbank.co.za/static/docs/cashout-create-order. I think i forgot to rename this variable

2025-01-14 15:02 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.ts
> +    // ##TODO: How to mock if another response comes back than status REDEEMABLE from the sandbox?
I meant how can we mock these statuses coming back from our mock service

export enum NedbankVoucherStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  REDEEMABLE = 'REDEEMABLE',
  REDEEMED = 'REDEEMED',
  REFUNDED = 'REFUNDED',
}

2025-01-14 15:09 UTC, RubenGeo commented on services/121-service/src/payments/payments.helpers.ts
> +export function generateUUIDFromSeed(seed: string): string {
Yes, I reacted to that [here](https://github.com/global-121/121-platform/pull/6293#discussion_r1910690893) ;)

I will implement it like this.

2025-01-14 15:27 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.ts
> +  }): Promise<CreateOrderResponseNedbankDto> {
Is this also what we want for private function inside an Api-service? For example in safaricom this works similair on makeTransferCall

2025-01-14 15:35 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.ts
> +            Identification: process.env.NEDBANK_ACCOUNT_NUMBER!, // ##TODO should we check somewhere if the .env is set?
Failed transactions ;). 

Like we could check if these envs are set in payment service for example. So you would not be able to start a payment if this var is not set. Not super sure if it's worth the effort

2025-01-14 15:42 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.ts
> +            Name: 'MyRefOnceOffQATrx', // ##TODO Not sure what to set here. Quote from the API word document from didirik: 'This is what shows on the SARCS statement. We can set this value for (manua
I am not I completely follow you here. 
- Would this name show up in the getVoucher response? 
- Where would we than show this to our users or is it for our azure logging?  
- Where would our users use this for? In their communication with nedbank?

2025-01-14 15:59 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.ts
> +    return (response as NedbankErrorResponse).Errors !== undefined;
It's called a [TypeGuard](https://blog.logrocket.com/how-to-use-type-guards-typescript/) and it's purpose is to narrow down the type a varaible so that in this case we can safely assume the type of the data we put in  the formatError function

2025-01-14 16:09 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.ts
> +  private formatError(responseBody: NedbankErrorResponse | null): string {
Not sure what you mean here. I can't find a formatError function or a safaricom helper file?

2025-01-15 08:24 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.ts
> +    // ##TODO is there a smart way to throw an error here if the .env is not set but the client does want to use nedbank? Or is that overengineering?
- So before a 500 error would happen in the transaction jobs processor flow. and the user would get zero feedback of this since no new transactions were created.

Now I implemented an error in the nedbankApiRequestOrThrow method that will create failed transactions. 
```throw new NedbankError(
        'Nedbank certificate has not been read. It could be that NEDBANK_CERTIFICATE_PATH or NEDBANK_CERTIFICATE_PASSWORD are not set or that certificate has not been uploaded to the server. Please contact 121 support',
      );
```

We could also consider adding all required .env variables for all FSP to the `FINANCIAL_SERVICE_PROVIDER_SETTINGS` settings const. And throw an error in the payment service before all jobs are put in the queue. 

But i think the other solution I created is good enough for now as this error will most likely not happen on production and generic solution will not trigger if a certificate has not been uploaded

2025-01-15 08:27 UTC, RubenGeo commented on services/121-service/src/queues-registry/queues-registry.module.ts
> +        duration: 1000, // per duration in milliseconds
Because 1000 ms is 1 second which is easy to understand for my brain ;)

2025-01-15 08:57 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.ts
> +      // ##TODO: If check here for 5000 and Nebank changes the max amount we need to change it here as well
I covered this with a unit test. I think this more a suitable in this case than an API test. What do you think?

2025-01-15 10:29 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/interfaces/nedbank-create-order-params.ts
> +  transactionReference: string;
So at first it's a transactionReference which is a string that consists of a concatinated values of:

referenceId + paymentNr + countOfFailedTransactions. 

and later on this is transformed to a uuid named: orderCreateReference which corresponds to the name used by the Nedbank API.

I named it transactionReference as to not confuse it with the orderCreateReference term used by nedbank. 

But maybe it makes more sense to name it `orderCreateReferenceSeed` as it's the seed that is used to generate the orderCreateReference

2025-01-15 12:17 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.ts
> +      // ##TODO: If check here for 5000 and Nebank changes the max amount we need to change it here as well
Yes I added an api test. The mock server return an error if you post an amount of over 5000

2025-01-15 12:29 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.ts
> +      // ##TODO: If check here for 5000 and Nebank changes the max amount we need to change it here as well
Now that I rethink this I realized that this messes with our retry functionality:

1. User send a transaction of 6000 to one registraiton
2. A failed transaction with amount 6000 is created
3. User retry's the payment and than that 6000 is re-used  (and can never be edited)

The same goes for payment amounts that are not a multiple of 10.

Do we accept that users would have to create a new payment in that case? If not we have to create some custom code in the payment service that throws a error if nedbank is included in your payments and the amounts are incorrect. (Or some way to edit the amount of retries.. which is even worse I think)

@tijsziere Is it a problem that users have to create a new payment if they input not a multiple of 10 as payment amount for Nedbank and they cannot retry?

2025-01-15 12:38 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-voucher.entity.ts
> +  @Column({ nullable: true, type: 'character varying' })
Not in our current code. 

This does make me think of something; it may be safer to store the orderCreateReference before we make the create order API call to nedbank. 

So if something goes wrong (we get a timeout from nedbank or we made a mistake parsing the response from nedbank), we still store the orderCreateReference (which is related to the actual money we pay nedbank). We can still later on use this orderCreateReference (for example in the nightly cronjob) to get the status of that money. If we manually have to debug we could also get this from our azure logs (hopefully)

2025-01-15 15:05 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.ts
> +      // ##TODO: If check here for 5000 and Nebank changes the max amount we need to change it here as well
I had a call with @tijsziere about this and we concluded that the workaround of doing a new payment is good enough for now.

2025-01-16 09:51 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/dtos/create-order-request-body-nedbank.dto.ts
Should that be in our guidelines? I did not create the nedbank-api subfolder because all of the dtos that are now in src/payments/fsp-integration/nedbank/dtos are related nedbank-api, , so creating a dedicated subfolder seemed redundant

2025-01-16 09:57 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-voucher.entity.ts
> +  @Column({ nullable: true, type: 'character varying' })
For now I set nullable to false

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/financial-sync/financial-sync-service.ts
> +              'Voucher has been refunded by Nedbank. Please contact Nedbank support.', // TODO: is this the correct ux copy?
Let's talk :)

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
> +import { generateUUIDFromSeed } from '@121-service/src/payments/payments.helpers';
My gut feel says: utils. As UUID stuff is not limited to HTTP and can be useful elsewhere. For example, we also generate UUIDs for Registration.referenceId, right?

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/dtos/create-order-request-body-nedbank.dto.ts
Great! Also updated the guidelines: https://github.com/global-121/121-platform/wiki/Guidelines-Software-Architecture#f-request-and-response-bodies-when-using-3rd-party-apis-eg-intersolve-api

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/interfaces/nedbank-create-order-params.ts
> +export interface NedbankCreateOrderParams {
I see your point. Let's briefly talk about this: refactor IntersolveVisa and Safaricom then. And perhaps call it CreateNedbankVoucherParams, to be more semantic.

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/interfaces/nedbank-create-order-params.ts
> +  transactionReference: string;
Let's talk about this.

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/interfaces/nedbank-create-order-return.ts
> +export interface NedbankCreateOrderReturn {
But then it would be NedbankCreateVoucherReturnType, right? And in light of my other comment: CreateNedbankVoucherReturnType.

> Why do we use ReturnType instead of Return?

Quite arbitrary choice. AFAIR to reduce of confusing "Response" with "Return".

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/interfaces/nedbank-create-order-return.ts
> +  orderCreateReference: string;
Yes.

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.ts
> +      // ##TODO: If check here for 5000 and Nebank changes the max amount we need to change it here as well
> Now that I rethink this I realized that this messes with our retry functionality:

I think that is the case whether we check for the 5000 limit or not in our job processor. So in that sense, another topic :)

We already talked about this, for me also fine.

Except for the multiple of 10: let's briefly talk about the consequences of "auto-correct".

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.ts
> +    const cashoutResult = await this.nedbankApiService.createOrder({
If "CashOut" is a term in Nedbank's domain, we could also adopt it in the Nedbank Module, if it serves a purpose. Let's talk briefly.

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.ts
> +    // ##TODO: How to mock if another response comes back than status REDEEMABLE from the sandbox?
Let's talk.

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.ts
> +  }): Promise<CreateOrderResponseNedbankDto> {
> Is this also what we want for private function inside an Api-service? 

This looks like a public function, not private.

For private functions my LOGAF is lower. Do we want this? It depends on the situation. for makeTransferCall I am fine with it.

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.ts
> +            Name: 'MyRefOnceOffQATrx', // ##TODO Not sure what to set here. Quote from the API word document from didirik: 'This is what shows on the SARCS statement. We can set this value for (manua
Let's talk.

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.ts
> +  private formatError(responseBody: NedbankErrorResponse | null): string {
Let's talk.

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.ts
> +    return errorMessage;
Yes. I would like to understand why that happens and what are the consequences for the caller/user.

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.ts
> +    // ##TODO is there a smart way to throw an error here if the .env is not set but the client does want to use nedbank? Or is that overengineering?
Let's talk.

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-voucher.entity.ts
> +  @Column({ nullable: true, type: 'character varying' })
Let's talk.

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/queues-registry/queues-registry.module.ts
> +        max: 5, // Max number of jobs processed
Can you briefly add this as a comment there? :)

2025-01-16 14:40 UTC, diderikvw commented on services/121-service/src/queues-registry/queues-registry.module.ts
> +        duration: 1000, // per duration in milliseconds
Why 1 second?

2025-01-16 14:52 UTC, RubenGeo commented on services/121-service/src/financial-sync/financial-sync-service.ts
> +        // ##TODO what extend should end the loop if something goes wrong?
We decided just to throw it. So we can find out if this ever goes wrong and than later change it

2025-01-16 15:01 UTC, RubenGeo commented on services/121-service/src/financial-sync/financial-sync-service.ts
> +              'Voucher has been refunded by Nedbank. Please contact Nedbank support.', // TODO: is this the correct ux copy?
We decided we are going to go for if (process.env.NEBANK_MOCK)  somewhere in the production code

2025-01-16 15:45 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.ts
> +  private formatError(responseBody: NedbankErrorResponse | null): string {
It's in the new unit test code

2025-01-16 15:58 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-voucher.entity.ts
> +  @Column({ nullable: true, type: 'character varying' })
Decided to store a voucher first here with null: 

![image](https://github.com/user-attachments/assets/e7743ecf-9af6-4aae-9456-2bfd68f962dc)

2025-01-16 15:58 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-voucher.entity.ts
> +  @Column({ nullable: true, type: 'character varying' })
Below system call Nedbank to create order

2025-01-16 16:02 UTC, RubenGeo commented on services/.env.example
> +PUBLIC_IP=
We decided that we need to test if the API actually requires this

2025-01-17 12:29 UTC, diderikvw requested changes
Reviewed unit tests.

2025-01-17 12:29 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.spec.ts
> +        await service.createOrder({
Why do we need to call service.createOrder twice in this test?

2025-01-17 12:29 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.spec.ts
> +    it('should throw an error if httpsAgent is not defined', async () => {
Is it worth the effort to test this? In other words: how can this happen?

Are this and above exhaustive in the error scenarios that can happen for createOrder?

In the Service I see: isNedbankErrorResponse(), with a lot of business logic that I do not see unit tested. Maybe that is not in this unit test file (where I would expect it though), but in the NedbankService unit test file. => For me personally simpler to find the unit test with the code, in this case, formatError as seperate unit implemented and tested.

2025-01-17 12:29 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.spec.ts
> +            Status: NedbankVoucherStatus.PENDING,
Is this the only status that can be returned from createOrder()? If so, great. If not, unit test them as well?

2025-01-17 12:29 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.spec.ts
> +      expect(requestCallArgs[0].url).toContain(`orders/references/`);
More of an integration test than unit test?

2025-01-17 12:29 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.spec.ts
> +      expect(requestCallArgs[0].method).toBe('GET');
More of an integration test than unit test?

2025-01-17 12:29 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.spec.ts
> +      expect(requestCallArgs[0].headers).toEqual(expect.any(Object));
Maybe more of an integration test than unit test?

2025-01-17 12:29 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.spec.ts
> +  describe('getOrder', () => {
Did you consider unit testing edge cases for the input parameter? Like an empty string, or very long text?

2025-01-17 12:29 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.ts
> +  private async nedbankApiRequestOrThrow<T>({
Did you consider unit testing this function(ality)?

2025-01-17 12:29 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.ts
> +  private createHttpsAgent(): https.Agent | undefined {
Did you consider unit testing this function(ality)?

2025-01-17 12:29 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.spec.ts
> +  describe('createOrder', () => {
Rename to createVoucher

2025-01-17 12:29 UTC, diderikvw commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.spec.ts
> +      const mockUUID = '12345678901234567890123456789012'; // Mock UUID
This should then fail, because this is not a valid UUID.

2025-01-17 12:29 UTC, diderikvw commented on services/121-service/src/transaction-job-processors/processors/transaction-job-nedbank.processor.spec.ts
> +  let paymentProcessor: TransactionJobProcessorNedbank;
Confusing var name

2025-01-17 12:29 UTC, diderikvw commented on services/121-service/src/transaction-job-processors/transaction-job-processors.service.spec.ts
Consider creating a helper service or helper methods for some of the more complex, stand-alone private functions in this Service and refactor unit testing accordingly.

2025-01-17 15:54 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.ts
> +  private createHttpsAgent(): https.Agent | undefined {
Consider testing this instead: createHttpsAgentWithCertificate

2025-01-21 10:05 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/interfaces/nedbank-create-order-params.ts
> +export interface NedbankCreateOrderParams {
Decided to park this in software architecture discussion

2025-01-21 14:44 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.spec.ts
> +      expect(requestCallArgs[0].method).toBe('GET');
Comment is outdated and I parked this in a ##TODO other discussion

2025-01-21 15:00 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.spec.ts
> +        { name: 'x-jws-signature', value: expect.any(String) },
Yes, good one. But I also think it's not worth the effort

2025-01-21 15:00 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.spec.ts
> +        { name: 'x-idempotency-key', value: expect.any(String) },
Yes, good one. But I also think it's not worth the effort

2025-01-21 15:01 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.spec.ts
> +          value: process.env.NEDBANK_CLIENT_SECRET,
Hmm not sure I see yet what would the benefit over this?

2025-01-21 15:02 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.spec.ts
> +        { name: 'x-ibm-client-id', value: process.env.NEDBANK_CLIENT_ID },
Same as [here](https://github.com/global-121/121-platform/pull/6293#discussion_r1923887374)

2025-01-21 15:07 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.spec.ts
> +      expect(requestCallParamObject.headers).toEqual([
Yes that would be a bit simpler, i now introduced the NedbankApiHelperService. So now this is tested on the `makeApiRequestOrThrow` method which it the public method of NedbankApiHelperService, which is a bit more logical than the createOrder method where is used to be before. 

I am doubting a bit of the value of unit testing the headers at al since there are no else/if/loops / other decisions made it in it. Maybe 'static typing' of typescript is enough of a test?

2025-01-21 15:13 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.spec.ts
> +        // ##TODO: this code contains some hardcoded strings, like ('recipient'), which are also hardcode in the actual service. Should we extract them to constants or just check if they are present?
I removed testing of the payload see also this [comment](https://github.com/global-121/121-platform/pull/6293#discussion_r1923896287)

2025-01-21 15:13 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank-api.service.spec.ts
> +      expect(requestCallParamObject.payload).toMatchObject({
I removed testing of the payload see also this [comment](https://github.com/global-121/121-platform/pull/6293#discussion_r1923896287)

2025-01-27 07:51 UTC, diderikvw requested changes
Intermediate result, 43/64 files viewed.

2025-01-27 07:57 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/dtos/nedbank-api/error-reponse-nedbank.dto.ts
> +export interface ErrorReponseNedbankDto {
You get a different response body in the case of nedbank

2025-01-27 08:08 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/errors/nedbank.error.ts
> +  public code: string | NedbankErrorCode | undefined;
It can also be a string because we do not know all Nedbank error codes as this is not clear from their API documentation. So the enum does not have all values the api from nedbank can return

2025-01-27 08:08 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/errors/nedbank.error.ts
> +  constructor(message?: string, code?: string | NedbankErrorCode) {
Same as here: https://github.com/global-121/121-platform/pull/6293#discussion_r1930114271

2025-01-27 08:49 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.ts
> +  ): Promise<{ status: NedbankVoucherStatus; errorMessage?: string }> {
I considered that first but this was difficult here because, the retrieveVoucherInfo or the equivalent of that function should return voucherStatus. But the decision of what the voucherStatus is depends on if a NedbankError is raised in the nedbankApiService. So by moving the try /catch to the reconciliation service the decision of what the voucherstatus is that we are going to store is divided over 2 different functions and services.

I did also consider writing a more generic error message in the NedbankService that not relates to doing a retry but than I thought this would be too confusing for the user. 

I think another solution could be that retrieveVoucherInfo returns:
```
{
  'status': NedbankVoucherStatus,
   'errorMessage': <the random string we get from nedbank>,
   'errorCode': <the error we get from Nedbank>
}
```
However I do think it would be nice if we sort of encapsulated the Nedbank Error codes in the nedbank module. So errorCode could also be replaced with 'voucherExistsAtNedbank' or something like this.

2025-01-27 08:55 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.ts
> +        // This situation can occur if:
Relates to this [discussion](https://github.com/global-121/121-platform/pull/6293#discussion_r1930160022)

2025-01-27 10:44 UTC, RubenGeo commented on services/121-service/src/reconciliation/nedbank-reconciliation/nedbank-reconciliation.service.ts
> +      await this.nedbankService.retrieveVoucherInfo(orderCreateReference);
Than you get an internal sever error and we get a 500 email. But in theory it should not happen as how the code is now

2025-01-27 10:45 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.ts
> +    } catch (error) {
I am not 100% sure I follow you here. Maybe we should discuss this

2025-01-27 13:37 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.ts
> +  ): Promise<{ status: NedbankVoucherStatus; errorMessage?: string }> {
In the end I thought of not implementing this solution with the added error code
{
  'status': NedbankVoucherStatus,
   'errorMessage': <the random string we get from nedbank>,
   'errorCode': <the error we get from Nedbank>
} 
because that would make the functionality where I parse the errorMessage much harder to unit tests as it would move to a private function in the nedbank reconciliation service

2025-01-29 12:46 UTC, diderikvw requested changes
Final batch of incremental review :)

2025-01-29 12:46 UTC, diderikvw commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
> +describe('Do payment to PA(s)', () => {
```suggestion
describe('Do payment', () => {
```
We do not use the term PA anymore.

2025-01-29 12:46 UTC, diderikvw commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
> +    describe('when create order API call gives a valid response', () => {
What is "valid"? Success? Because an error response can also be valid.

2025-01-29 12:46 UTC, diderikvw commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
> +      it('should succesfully pay-out', async () => {
```suggestion
      it('should succesfully do a payment', async () => {
```

2025-01-29 12:46 UTC, diderikvw commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
> +        await runCronjobUpdateNedbankVoucherStatus();
Why run this cron job as part of testing do payment? Should testing the cron job not be a separate integration test? Or if it should be here, then the name of the test may not cover what it actually does.

2025-01-29 12:46 UTC, diderikvw commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
> +        await runCronjobUpdateNedbankVoucherStatus();
```suggestion
        await runCronJobDoNedbankReconciliation();
```

2025-01-29 12:46 UTC, diderikvw commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
> +        const exportPaymentResponse = await exportList({
Why not test the export in a seperate test?

2025-01-29 12:46 UTC, diderikvw commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
> +      it('should fail pay-out when debitor account number is missing', async () => {
```suggestion
      it('should create a transaction with status error when phone number is missing', async () => {
```

2025-01-29 12:46 UTC, diderikvw commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
> +      it('should fail pay-out when we make a payment with a payment amount of over 5000', async () => {
```suggestion
      it('should create a transaction with status error when we make a payment with a payment amount of over 5000', async () => {
```

2025-01-29 12:46 UTC, diderikvw commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
> +      it('should set transaction status to error in reconciliation process if phonenumber is incorrect', async () => {
How can the phone number turn out to be incorrect during reconciliation? We send the phone number when creating the order, so if it was not correct, it would have raised an error then, right?

2025-01-29 12:46 UTC, diderikvw commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
> +      it('should create a new order reference on a retry payment', async () => {
```suggestion
      it('should create a voucher with a new orderCreateReference on a retry payment', async () => {
```

2025-01-29 12:46 UTC, diderikvw commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
Related to Integration Test covering "happy paths" and "expected paths during production": also include scenarios that are expected, like:
1. env var(s) not (correctly) set
2. ProgramFSpConfig(s) not (correctly) set
3. Certificate missing or incorrect
4. Configuration on Nedbank's end not (correctly) set for this client/project.
5. Credentials not successfully authenticating in Nedbank's API
6. ...

2025-01-29 12:46 UTC, diderikvw commented on services/mock-service/src/fsp-integration/nedbank/nedbank.mock.service.ts
> +      // ##TODO: discuss if we can find a more elegant way to simulate a timeout error
Looks fine to me. What is not clean about this solution?

2025-01-31 07:56 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/enums/nedbank-voucher-status.enum.ts
> +  FAILED = 'FAILED', // This status is used in the 121-platform to indicate that the voucher failed to be created because we got an error response from Nedbank
I think it's easiest if we separate out the nedbank order and the nedbank voucher in our code in either 2 separate entities or an entity that stores both voucherStatus and orderStatus. Than an order can fail without a voucher being created, which is actually what happens at nedbank side. 

We can merge the 2 statusses later if needed like we do for Intersolve Visa on the payment export.

2025-01-31 08:26 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/repositories/nedbank-voucher.scoped.repository.ts
> +  public async storeVoucher({
When I used save directly on an object it gives this type error: 

```  Overload 1 of 4, '(entity: NedbankVoucherEntity, options?: SaveOptions | undefined): Promise<NedbankVoucherEntity>', gave the following error.
    Argument of type '{ paymentReference: string; orderCreateReference: string; status: NedbankVoucherStatus | null; transactionId: number; }' is not assignable to parameter of type 'NedbankVoucherEntity'.
      Type '{ paymentReference: string; orderCreateReference: string; status: NedbankVoucherStatus | null; transactionId: number; }' is missing the following properties from type 'NedbankVoucherEntity': transaction, id, created, updated ```

It's mainly complaining about created and updated messing. To avoid these sort of error we often use something like 

```
    const newIntersolveVisaParentWallet =
      new IntersolveVisaParentWalletEntity();
    newIntersolveVisaParentWallet.intersolveVisaCustomer =
      intersolveVisaCustomer;
    newIntersolveVisaParentWallet.tokenCode = issueTokenResult.code;
    newIntersolveVisaParentWallet.lastExternalUpdate = new Date();
```
But I find using .create more readable. According to typeorm [docs](https://github.com/typeorm/typeorm/blob/master/docs/repository-api.md)  it does the same thing

2025-01-31 10:01 UTC, RubenGeo commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
> +      it('should set transaction status to error in reconciliation process if phonenumber is incorrect', async () => {
That test scenario is mainly there to check if we handle Nedbank errors in the reconciliation process correctly. This is the only error I got from the Nedbank Api on reconciliation, until the insufficient fund error of the acceptance test. But I did not store that error text/body, so I think using the error is most pratical. 

There could also be other validation on phonenumber happening at Nedbank.

2025-01-31 10:10 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/repositories/nedbank-voucher.scoped.repository.ts
> +  }): Promise<NedbankVoucherEntity | null> {
I think it makes more sense to return null here. 

> undefined indicates a variable hasn't been initialized, while null is intentionally assigned to indicate no value

Also typeorm's findOne returns null

2025-01-31 10:54 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/services/nedbank-api.helper.service.ts
> +  public async makeApiRequestOrThrow<T>({
I like the split now because:

- **NedbankApiService handles business logic**, while **NedbankApiHelperService deals with low-level API communication**.  
  - `NedbankApiService` knows about the specific API calls (`createOrder` and `getOrderByReference`) and processes the response.  
  - `NedbankApiHelperService` has the shared logic used by both API calls.  

- Making `makeApiRequestOrThrow` **public** is nice because:  
  - It can now be **unit tested** on its own.  
  - It’s used in multiple places, so testing it separately makes sense.  
  - This is different from Safaricom, where there’s only one API call.
  -

- I get the point that **"Helper" makes it sound like the service is stateless**, which isn’t really the case.  
  - A good way to fix this could be to introduce a `NedbankApiClientService` and move `makeApiRequestOrThrow` there.  
  - Or just rename `NedbankApiHelperService` to `NedbankApiClientService`, which keeps things simple.  

- I do think `createOrderPayload` belongs in `NedbankApiService` because it’s **tied to a specific API request**.  
  - A client/helper service should be more about reusable code, not request-specific logic.

2025-01-31 11:03 UTC, RubenGeo commented on services/121-service/test/helpers/registration.helper.ts
> +  await doPayment(programId, 1, 20, [], accessToken, {
> What is this change about?

Nedbank Api get angry if do not do a multiple of 10. So I changed this here to a defeault value that works for every FSP

> And let's deconstruct the params into an object, which will make reading this much easier.

Agreed, my current approach in refactoring deconstructed parameters in existing code is to do that when I change the params a function has as input. So in this case I just left it as the doPayment function  tself was not touched.

2025-01-31 11:06 UTC, RubenGeo commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
> +    describe('when create order API call gives a valid response', () => {
Exactly, I mean here a (valid) success  or a (valid) error response. (So not a timeout).

2025-01-31 13:00 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.ts
> +          'Voucher has been refunded by Nedbank. If you retry this transfer, the person will receive a new voucher.';
Yes, we should discuss a solution for this it relates to : [this](https://github.com/global-121/121-platform/pull/6293#discussion_r1930541415) and the [failed status discussion](https://github.com/global-121/121-platform/pull/6293#discussion_r1930706592)

2025-01-31 13:19 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/services/nedbank-api.helper.service.ts
> +  private createHttpsAgent(): https.Agent | undefined {
Relates to this comment about the responsibility of [the helper](https://github.com/global-121/121-platform/pull/6293#discussion_r1937044521)

2025-01-31 13:19 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/services/nedbank-api.service.ts
> +//##TODO Discuss: I decided to not have unit tests for this service because all the functions are just calling the helper service
Relates to this comment about the responsibility of [the helper](https://github.com/global-121/121-platform/pull/6293#discussion_r1937044521)

2025-01-31 13:21 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/services/nedbank-api.helper.service.ts
> +  public httpsAgent: https.Agent | undefined;
Relates to this comment about the responsibility of [the helper](https://github.com/global-121/121-platform/pull/6293#discussion_r1937044521)

2025-01-31 13:32 UTC, RubenGeo commented on services/121-service/src/payments/transactions/transaction.repository.ts
> +  public async getFailedTransactionsCount({
yes 😆 , I this .count used to be a querybuilder and i left it there

2025-01-31 13:33 UTC, RubenGeo commented on services/121-service/src/transaction-job-processors/transaction-job-processors.service.spec.ts
> +  // ##TODO: Discuss if this adds anything beyond the integration tests
Relates to this comment about the responsibility of [the helper](https://github.com/global-121/121-platform/pull/6293#discussion_r1937044521)

2025-01-31 13:37 UTC, RubenGeo commented on services/mock-service/src/fsp-integration/nedbank/nedbank.mock.service.ts
> +      // ##TODO: discuss if we can find a more elegant way to simulate a timeout error
There is not an actual timeout happening maybe something unexpected happens here. Maybe something unexpected happens if we change the way we handle timeouts in the 121-service in general. But I think it's hard to simulate this precisely and it's also a relevant scenario for all other fsps, I guess it's easier to just leave it like this.

2025-01-31 13:43 UTC, RubenGeo commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
I think it's good to discuss this. The trade of between the value of these scenario's vs the cost (of running them on all PRs and creating maintaining them)

2025-01-31 14:36 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/services/nedbank-api.service.ts
> +    const getOrderUrl = !!process.env.MOCK_NEDBANK
```  const getOrderUrl = !!process.env.MOCK_NEDBANK
      ? `${process.env.MOCK_SERVICE_URL}api/fsp/nedbank/v1/orders/references/${orderCreateReference}`
      : `${process.env.NEDBANK_API_URL}/v1/orders/references/${orderCreateReference}`;```  

Move this to makeApiRequestOrThrow (see intersolve visa service)

2025-01-31 14:45 UTC, RubenGeo commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
I'll go over each scenario and consider testing it manually again.

2025-01-31 14:49 UTC, RubenGeo commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
> +        await runCronjobUpdateNedbankVoucherStatus();
I'll change the name

2025-02-04 09:26 UTC, RubenGeo commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
1. You get an error in the 
![image](https://github.com/user-attachments/assets/89be5984-2ca2-4e8b-b23c-58dbb6e0cb2a). Parsing unexpected error formats is covered by a unit test
2. added an api test for this
3. If the  NEDBANK_CERTIFICATE_PATH is set but does not point to a file, the app will not start up. Which is fine I think because it can only be managed by us. NEDBANK_CERTIFICATE_PASSWORD you do not use in the azure app service.  If you use the sandbox certificate for the QA server you get this failed transaction: 
![image](https://github.com/user-attachments/assets/dd7e20c4-4727-413d-beee-41216739c493). Which is not so clear but it is also not likely to happen as the certificate is set by us
4. I do not know what happens here
5. Similar results to nr. 1

2025-02-05 10:22 UTC, diderikvw requested changes
Great work! I think we are almost there! :)

2025-02-05 10:22 UTC, diderikvw commented on services/121-service/src/reconciliation/nedbank-reconciliation/nedbank-reconciliation.service.ts
Do we not want to unit test this service?

2025-02-05 10:22 UTC, diderikvw commented on services/121-service/src/transaction-job-processors/transaction-job-processors.service.ts
> +    ); // All non-alphanumeric characters are removed because the nedbank API does not accept them
Plus dashes?
And should we document adding FspConfig and this behavior here?
https://github.com/global-121/121-platform/wiki/Nedbank

2025-02-05 10:22 UTC, diderikvw commented on services/121-service/test/helpers/utility.helper.ts
> +export async function runCronJobDoNedbankReconciliation(): Promise<void> {
Does this still have value with introducing the cronjobs integration test?

2025-02-05 10:22 UTC, diderikvw commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
Would it be helpful to mention the somewhat cryptic error messages here + what they mean?
https://github.com/global-121/121-platform/wiki/Nedbank

2025-02-05 11:02 UTC, RubenGeo commented on services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
In think the invalid client and secret error speaks for itself. The other one I added to this readme about setting up the certificate: src/payments/fsp-integration/nedbank/README.md. And than we will move it to somewhere else once we resolve this [discussion](https://dev.azure.com/redcrossnl/121%20Platform/_sprints/taskboard/121%20Development%20Team/121%20Platform/Sprint%20148?workitem=32412)

2025-02-05 11:11 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.ts
> +        throw new NedbankError(error.message, NedbankErrorCode.genericApiError);
I just throw the generic error here if there is an api error that does have to handled in a specific way in the consumer(s) of the NedbankService.

> But if the list NedbankApiErrorCode is extended, a translation from NedbankApiError to NedbankError would need to happen, right?

I think this is only needed if the consumer of the nedbank service needs to handle something differently or if we think it makes the code more readable. 

We could also do here without the NedbankErrorCode.invalidParameter and rename NedbankErrorCode.genericApiError to genericError. As we do not really do anything differently in the TransactionJobsProcessor with those error code. But I thought the genericApiError seemed clearer for the NedbankReconciliation service and than that name was not suitable for the invalidParameter error thrown in createVoucher

2025-02-05 12:41 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/nedbank.service.spec.ts
> +  });
Good one :). I am adding it

2025-02-05 13:02 UTC, RubenGeo commented on services/121-service/src/payments/fsp-integration/nedbank/services/nedbank-api-client.service.ts
> +        'Nedbank certificate has not been read. It could be that NEDBANK_CERTIFICATE_PATH or NEDBANK_CERTIFICATE_PASSWORD are not set or that the certificate has not been uploaded to the server. Plea
the problem is that createHttpsAgent is in the constructor, so you would get an error on startup of the app and not as a failed transaction. I put it in the constructor for performance reasons else you need to read and decrypt a file for every api call.

I think this is these are the most likely causes and I thought these pointers are better than saying something generic like: 'Something is wrong with the certificate'. Do you have other UX copy suggestions?

2025-02-05 13:09 UTC, RubenGeo commented on services/121-service/src/reconciliation/nedbank-reconciliation/nedbank-reconciliation.service.ts
I think all paths are covered by the integration test. Only the typeorm query is not completely tested by the integration tests, but I don't think that is feasable with a unit test or integration test.

A scenario you could have to test the query with an integration test is that when you rerun the cronjob the transaction and attached voucher that have the statusses (Succes and REDEEMED) are not updated again. I don't think that is super valuable though. 

What do you think? Do you think we miss another scenario?

2025-02-05 13:29 UTC, RubenGeo commented on services/121-service/test/helpers/utility.helper.ts
> +export async function runCronJobDoNedbankReconciliation(): Promise<void> {
Yes. It's used frequently to test the reconciliation flow in our integration tests

2025-02-05 13:54 UTC, diderikvw approved these changes

2025-02-07 09:34 UTC, diderikvw approved these changes

2025-02-07 15:35 UTC, merged