fix: make make programFspConfigId nullable in relations AB#32262
global-121/121-platform pull request #6306
Opened 2024-12-18 13:22 UTC by jannisvisser

AB#32262

## Describe your changes

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added tests wherever relevant
- [ ] I have made sure that all automated checks pass before requesting a review
- [ ] I do not need any deviation from our PR guidelines

2024-12-23 12:52 UTC, RubenGeo requested changes
See the PR I made to this branch

2024-12-24 08:21 UTC, RubenGeo commented
I think we should wait for this [task](https://dev.azure.com/redcrossnl/121%20Platform/_sprints/taskboard/121%20Development%20Team/121%20Platform/Sprint%20144?workitem=32262) before we merge this.

2025-01-06 08:49 UTC, jannisvisser commented
@RubenGeo you still need to get this PR merged (I see the item is already on 'to accept'). The PR you just merged was a sub-PR.

2025-01-24 13:44 UTC, RubenGeo approved these changes

2025-01-24 13:54 UTC, merged